// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFPMr8HGXZpG9ptf9jglX7Q9ue6b5YSZo',
    appId: '1:646990367359:web:9606eda246d872fb29cd4a',
    messagingSenderId: '646990367359',
    projectId: 'internet-billing-fsd',
    authDomain: 'internet-billing-fsd.firebaseapp.com',
    storageBucket: 'internet-billing-fsd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHtZSwnbdopmG3HbQoGeYyhFcM4yz7Eoc',
    appId: '1:646990367359:android:0882cb847887a07829cd4a',
    messagingSenderId: '646990367359',
    projectId: 'internet-billing-fsd',
    storageBucket: 'internet-billing-fsd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtMkeNuM4XB_a62pn5cnEGsgbVxkC0tTg',
    appId: '1:646990367359:ios:1adeb80132c5688429cd4a',
    messagingSenderId: '646990367359',
    projectId: 'internet-billing-fsd',
    storageBucket: 'internet-billing-fsd.firebasestorage.app',
    iosBundleId: 'com.example.internetBilling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtMkeNuM4XB_a62pn5cnEGsgbVxkC0tTg',
    appId: '1:646990367359:ios:1adeb80132c5688429cd4a',
    messagingSenderId: '646990367359',
    projectId: 'internet-billing-fsd',
    storageBucket: 'internet-billing-fsd.firebasestorage.app',
    iosBundleId: 'com.example.internetBilling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFPMr8HGXZpG9ptf9jglX7Q9ue6b5YSZo',
    appId: '1:646990367359:web:d8cb60a4e738b85d29cd4a',
    messagingSenderId: '646990367359',
    projectId: 'internet-billing-fsd',
    authDomain: 'internet-billing-fsd.firebaseapp.com',
    storageBucket: 'internet-billing-fsd.firebasestorage.app',
  );
}
