import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class BillsScreen extends StatefulWidget {
  final List<dynamic> bills;
  final List<dynamic> users;
  final VoidCallback onUpdate;
  final VoidCallback onUsersUpdate;
  final Function(Map<String, dynamic>) onCollectionAdd;

  const BillsScreen({super.key, required this.bills, required this.users, required this.onUpdate, required this.onUsersUpdate, required this.onCollectionAdd});

  @override
  State<BillsScreen> createState() => _BillsScreenState();
}

class _BillsScreenState extends State<BillsScreen> {
  String filter = "All";
  String search = "";
  final TextEditingController searchCtrl = TextEditingController();
  final _firestore = FirebaseFirestore.instance;
  String get uid => FirebaseAuth.instance.currentUser!.uid;

  @override
  void initState() {
    super.initState();
    Future.microtask(() => autoGenerateExpiredBills());
  }

  List<dynamic> get filteredBills => widget.bills.where((b) {
    bool matchFilter = filter == "All" || (filter == "Paid" && b['isPaid'] == true) || (filter == "Pending" && b['isPaid']!= true);
    bool matchSearch = search.isEmpty || b['name'].toString().toLowerCase().contains(search.toLowerCase());
    bool userExists = widget.users.any((u) => u['phone'].toString() == b['phone'].toString());
    if (!userExists) return false;
    return matchFilter && matchSearch;
  }).toList();

  Future<void> autoGenerateExpiredBills() async {
    DateTime now = DateTime.now();
    String currentMonthKey = "${now.year}-${now.month}";
    bool newBillAdded = false;
    for (var user in widget.users) {
      bool isExpired = false;
      if (user['expiryDate']!= null) {
        try {
          DateTime expiryDate = DateTime.fromMillisecondsSinceEpoch(user['expiryDate']);
          if (now.isAfter(expiryDate)) isExpired = true;
        } catch (e) {}
      }
      if (isExpired) {
        bool billExists = widget.bills.any((b) => b['phone'].toString() == user['phone'].toString() && b['billMonth'] == currentMonthKey);
        if (!billExists) {
          var newBill = {
            'name': user['name'],
            'phone': user['phone'].toString(),
            'amount': user['amount']?? 1000,
            'package': user['package']?? '10 Mbps',
            'isPaid': false,
            'date': now.toIso8601String(),
            'billMonth': currentMonthKey,
            'createdAt': now.millisecondsSinceEpoch,
            'autoGenerated': true
          };
          widget.bills.add(newBill);
          // Firebase پر بھی سیو کریں - یہ آپ کے main logic کے لیے ضروری ہے
          String id = "${newBill['phone']}_${newBill['billMonth']}_${newBill['createdAt']}";
          await _firestore.collection('isps').doc(uid).collection('my_bills').doc(id).set(newBill);
          newBillAdded = true;
        }
      }
    }
    widget.bills.removeWhere((b) =>!widget.users.any((u) => u['phone'].toString() == b['phone'].toString()));
    setState(() {});
    if (newBillAdded) widget.onUpdate();
  }

  DateTime calculateExpiryPreserveDay(DateTime oldExpiry) {
    int year = oldExpiry.year;
    int month = oldExpiry.month + 1;
    if (month > 12) { month = 1; year++; }
    int day = oldExpiry.day;
    int lastDay = DateTime(year, month + 1, 0).day;
    if (day > lastDay) day = lastDay;
    DateTime newExpiry = DateTime(year, month, day);
    DateTime now = DateTime.now();
    DateTime today = DateTime(now.year, now.month, now.day);
    while (newExpiry.isBefore(today)) {
      year = newExpiry.year;
      month = newExpiry.month + 1;
      if (month > 12) { month = 1; year++; }
      day = oldExpiry.day;
      lastDay = DateTime(year, month + 1, 0).day;
      if (day > lastDay) day = lastDay;
      newExpiry = DateTime(year, month, day);
    }
    return newExpiry;
  }

  Future<void> extendUserExpiry(String phone) async {
    try {
      for (var u in widget.users) {
        if (u['phone'].toString() == phone.toString()) {
          DateTime oldExpiry;
          if (u['expiryDate']!= null) {
            oldExpiry = DateTime.fromMillisecondsSinceEpoch(u['expiryDate']);
          } else {
            oldExpiry = DateTime.now();
          }
          DateTime newExpiry = calculateExpiryPreserveDay(oldExpiry);
          u['expiry'] = newExpiry.toIso8601String().split('T')[0];
          u['expiryDate'] = newExpiry.millisecondsSinceEpoch;
          u['isActive'] = true;
          await _firestore.collection('isps').doc(uid).collection('my_users').doc(phone.toString()).update({
            'expiry': u['expiry'],
            'expiryDate': u['expiryDate'],
            'isActive': true,
          });
          break;
        }
      }
      widget.onUsersUpdate();
    } catch (e) {
      print("Expiry extend error: $e");
    }
  }

  Future<void> deleteBillFromFirebase(Map<String,dynamic> bill) async {
    try {
      String phone = bill['phone']?.toString()?? "unknown";
      String month = bill['billMonth']?.toString()?? "";
      String created = bill['createdAt']?.toString()?? "";
      String id = "${phone}_${month}_$created".replaceAll('/', '_');
      await _firestore.collection('isps').doc(uid).collection('my_bills').doc(id).delete();

      if(created.isEmpty){
        var snap = await _firestore.collection('isps').doc(uid).collection('my_bills').where('phone', isEqualTo: phone).where('billMonth', isEqualTo: month).get();
        for(var d in snap.docs){ await d.reference.delete(); }
      }
    } catch(e){
      print("delete bill error $e");
    }
  }

  void showPaymentDialog(var bill, int realIndex) {
    TextEditingController paidCtrl = TextEditingController(text: bill['amount'].toString());
    showDialog(context: context, builder: (c) => AlertDialog(
      backgroundColor: const Color(0xFF1E1E1E),
      title: Text("${bill['name']} - Fee Jama", style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold)),
      content: Column(mainAxisSize: MainAxisSize.min, children: [
        Text("Total Bill: Rs. ${bill['amount']}", style: const TextStyle(color: Colors.white70)),
        const SizedBox(height: 12),
        TextField(controller: paidCtrl, keyboardType: TextInputType.number, style: const TextStyle(color: Colors.white), decoration: InputDecoration(labelText: "How Much Paid? Rs.", labelStyle: const TextStyle(color: Colors.white54), filled: true, fillColor: const Color(0xFF2A2A2A), border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)))),
      ]),
      actions: [
        TextButton(onPressed: ()=>Navigator.pop(c), child: const Text("Cancel")),
        ElevatedButton(style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF7C4DFF)), onPressed: () async {
          double total = double.tryParse(bill['amount'].toString())?? 0;
          double paid = double.tryParse(paidCtrl.text)?? 0;
          if(paid <= 0) return;
          final now = DateTime.now();

          for (var u in widget.users) {
            if (u['phone'].toString() == bill['phone'].toString()) {
              u['pendingDue'] = paid >= total ? 0 : (total - paid);
              await _firestore.collection('isps').doc(uid).collection('my_users').doc(u['phone'].toString()).update({
                'pendingDue': u['pendingDue'],
              });
              break;
            }
          }

          await extendUserExpiry(bill['phone']);
          await deleteBillFromFirebase(bill);

          widget.onCollectionAdd({
            "name": bill['name'],
            "phone": bill['phone'].toString(),
            "amount": paid,
            "package": bill['package'],
            "date": now.toIso8601String(),
            "billMonth": "${now.year}-${now.month}",
            "type": paid >= total? "full" : "partial",
            "id": now.millisecondsSinceEpoch.toString()
          });

          setState(()=> widget.bills.removeAt(realIndex));
          widget.onUpdate();
          widget.onUsersUpdate();
          Navigator.pop(c);
          ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(paid >= total? "${bill['name']} Full Paid & Deleted!" : "Rs. $paid Collected"), backgroundColor: Colors.green));
        }, child: const Text("Collect"))
      ],
    ));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF121212),
      appBar: AppBar(backgroundColor: const Color(0xFF121212), title: Text("Bills - ${filteredBills.length}", style: GoogleFonts.poppins(color: Colors.white, fontWeight: FontWeight.bold)), actions: [IconButton(icon: const Icon(Icons.refresh), onPressed: autoGenerateExpiredBills)]),
      body: Column(children: [
        Padding(padding: const EdgeInsets.all(12), child: TextField(controller: searchCtrl, style: const TextStyle(color: Colors.white), onChanged: (v)=>setState(()=>search=v), decoration: InputDecoration(hintText: "Search user...", hintStyle: const TextStyle(color: Colors.white38), prefixIcon: const Icon(Icons.search, color: Colors.white38), filled: true, fillColor: const Color(0xFF1E1E1E), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none)))),
        Row(children: [const SizedBox(width: 12), _filterChip("All"), _filterChip("Pending")]),
        const SizedBox(height: 10),
        Expanded(child: ListView.builder(itemCount: filteredBills.length, itemBuilder: (c, i) {
          var b = filteredBills[i];
          int realIndex = widget.bills.indexWhere((x) => x['phone'].toString() == b['phone'].toString() && x['billMonth'] == b['billMonth']);
          if(realIndex == -1) realIndex = widget.bills.indexOf(b);
          return Container(margin: const EdgeInsets.symmetric(horizontal: 12, vertical: 6), decoration: BoxDecoration(color: const Color(0xFF1E1E1E), borderRadius: BorderRadius.circular(15)), child: ListTile(leading: const CircleAvatar(backgroundColor: Colors.orange, child: Icon(Icons.pending, color: Colors.white)), title: Text(b['name'], style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)), subtitle: Text("${b['package']??''} - Rs. ${b['amount']}", style: const TextStyle(color: Colors.white54, fontSize: 11)), trailing: IconButton(icon: const Icon(Icons.payments, color: Colors.greenAccent), onPressed: ()=>showPaymentDialog(b, realIndex))));
        })),
      ]),
    );
  }
  Widget _filterChip(String label) => Padding(padding: const EdgeInsets.only(right: 8), child: ChoiceChip(label: Text(label), selected: filter == label, selectedColor: const Color(0xFF7C4DFF), backgroundColor: const Color(0xFF2A2A2A), labelStyle: const TextStyle(color: Colors.white), onSelected: (v)=>setState(()=>filter=label)));
}