import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../services/firebase_service.dart';
import '../utils/app_strings.dart';

class BillsScreen extends StatefulWidget {
  final List<dynamic> bills;
  final List<dynamic> users;
  final List<dynamic> collections;
  final VoidCallback onUpdate;
  final VoidCallback onUsersUpdate;
  final Function(Map<String, dynamic>) onCollectionAdd;
  final Function(String) onCollectionRemove;
  const BillsScreen({super.key, required this.bills, required this.users, this.collections = const [], required this.onUpdate, required this.onUsersUpdate, required this.onCollectionAdd, required this.onCollectionRemove});
  @override
  State<BillsScreen> createState() => _BillsScreenState();
}

class _BillsScreenState extends State<BillsScreen> {
  String filter = "All";
  String search = "";
  String selectedMonthFilter = "${DateTime.now().year}-${DateTime.now().month}";
  final TextEditingController searchCtrl = TextEditingController();

  List<dynamic> get filteredBills => widget.bills.where((b) {
    bool matchFilter = filter == "All" || (filter == "Paid" && b['isPaid'] == true) || (filter == "Pending" && b['isPaid']!= true);
    bool matchSearch = search.isEmpty || b['name'].toString().toLowerCase().contains(search.toLowerCase()) || b['phone'].toString().contains(search);
    bool matchMonth = b['billMonth'] == selectedMonthFilter;
    // Deleted user toggle - ab bill chupta nahi, dikhta hai
    return matchFilter && matchSearch && matchMonth;
  }).toList();

  List<String> get last12Months {
    List<String> months = [];
    DateTime now = DateTime.now();
    for(int i=0; i<12; i++){
      DateTime d = DateTime(now.year, now.month - i, 1);
      months.add("${d.year}-${d.month}");
    }
    return months;
  }

  Future<void> autoGenerateExpiredBills() async {
    DateTime now = DateTime.now();
    String currentMonthKey = "${now.year}-${now.month}";
    bool newBillAdded = false;
    for (var user in widget.users) {
      bool isExpired = false;
      if (user['expiryDate']!= null) {
        try { DateTime expiryDate = DateTime.fromMillisecondsSinceEpoch(user['expiryDate']); if (now.isAfter(expiryDate)) isExpired = true; } catch (e) {}
      }
      if (isExpired) {
        bool billExists = widget.bills.any((b) => b['phone'].toString() == user['phone'].toString() && b['billMonth'] == currentMonthKey);
        if (!billExists) {
          var newBill = {'name': user['name'], 'phone': user['phone'].toString(), 'amount': user['amount']?? 1000, 'package': user['package']?? '10 Mbps', 'isPaid': false, 'date': now.toIso8601String(), 'billMonth': currentMonthKey, 'createdAt': now.millisecondsSinceEpoch, 'autoGenerated': true, 'id': FirebaseService.genBillId(user['phone'].toString(), currentMonthKey)};
          widget.bills.add(newBill);
          await FirebaseService.billsCol.doc(newBill['id']).set(newBill);
          newBillAdded = true;
        }
      }
    }
    setState(() {});
    if (newBillAdded) widget.onUpdate();
  }

  Future<void> showBillPdf(Map<String, dynamic> bill) async {
    final pdf = pw.Document();
    pdf.addPage(pw.Page(pageFormat: PdfPageFormat.a4, build: (context) => pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      pw.Container(color: PdfColors.deepPurple, padding: pw.EdgeInsets.all(12), child: pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [pw.Text(AppStrings.company, style: pw.TextStyle(color: PdfColors.white, fontSize: 22, fontWeight: pw.FontWeight.bold)), pw.Text("INTERNET BILL", style: pw.TextStyle(color: PdfColors.white, fontSize: 14))])),
      pw.SizedBox(height: 20),
      pw.Text("Customer: ${bill['name']}", style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
      pw.Text("Phone: ${bill['phone']} | Package: ${bill['package']}"),
      pw.Text("Amount: Rs. ${bill['amount']} | Month: ${bill['billMonth']}"),
      pw.Divider(),
      pw.Text("Thank you for using ${AppStrings.company}!", style: pw.TextStyle(fontSize: 10)),
    ])));
    await Printing.layoutPdf(onLayout: (format) async => pdf.save());
  }

  void _showUndoList(String? month) {
    String targetMonth = month?? selectedMonthFilter;
    TextEditingController undoSearchCtrl = TextEditingController();
    String undoSearch = "";
    String dropdownMonth = targetMonth;

    showModalBottomSheet(context: context, backgroundColor: const Color(0xFF1E1E1E), isScrollControlled: true, shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))), builder: (c){
      return StatefulBuilder(builder: (context, setSheetState){
        return FutureBuilder<QuerySnapshot>(future: FirebaseService.collectionsCol.where('billMonth', isEqualTo: dropdownMonth).get(), builder: (context, snapshot){
          List<dynamic> collectionsList = [];
          if(snapshot.hasData){ collectionsList = snapshot.data!.docs.map((d){ var data = d.data() as Map<String, dynamic>; data['docId'] = d.id; return data; }).toList(); }
          List<dynamic> filteredUndo = collectionsList.where((col){ if(undoSearch.isEmpty) return true; return col['name'].toString().toLowerCase().contains(undoSearch.toLowerCase()) || col['phone'].toString().contains(undoSearch); }).toList();
          return Container(padding: const EdgeInsets.all(16), height: 650, child: Column(children: [
            Container(width: 40, height: 4, decoration: BoxDecoration(color: Colors.grey[700], borderRadius: BorderRadius.circular(10))),
            const SizedBox(height: 12),
            Row(children: [
              Expanded(child: Text('Undo - Wasool Shuda', style: GoogleFonts.poppins(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 14))),
              DropdownButton<String>(value: dropdownMonth, dropdownColor: Color(0xFF2A2A2A), style: TextStyle(color: Colors.white, fontSize: 12), items: last12Months.map((m)=> DropdownMenuItem(value: m, child: Text(m))).toList(), onChanged: (v){ if(v!=null) setSheetState(()=> dropdownMonth=v); })
            ]),
            Text('Kul: ${collectionsList.length} | Filtered: ${filteredUndo.length} | Month: $dropdownMonth', style: GoogleFonts.poppins(color: Colors.white54, fontSize: 11)),
            const SizedBox(height: 10),
            TextField(controller: undoSearchCtrl, style: const TextStyle(color: Colors.white, fontSize: 13), onChanged: (v){ setSheetState(()=> undoSearch=v); }, decoration: InputDecoration(hintText: "Search Naam/Phone...", hintStyle: const TextStyle(color: Colors.white38, fontSize: 12), prefixIcon: const Icon(Icons.search, color: Colors.white54, size: 18), filled: true, fillColor: const Color(0xFF2A2A2A), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none))),
            const SizedBox(height: 10),
            Expanded(child: filteredUndo.isEmpty? Center(child: Text(AppStrings.noBill, style: GoogleFonts.poppins(color: Colors.white54))) : ListView.builder(itemCount: filteredUndo.length, itemBuilder: (c,i){
              var col=filteredUndo[i];
              bool userExists = widget.users.any((u)=> u['phone'].toString()==col['phone'].toString());
              return Card(color: userExists? const Color(0xFF2A2A2A) : const Color(0xFF3A2A2A), child: ListTile(leading: Icon(userExists? Icons.check_circle : Icons.person_off, color: userExists? Colors.green : Colors.redAccent), title: Text(col['name'].toString(), style: GoogleFonts.poppins(color: Colors.white, fontSize: 13)), subtitle: Text('Rs ${col['amount']} - ${col['billMonth']} - ${col['phone']}${userExists? '' : ' (User Deleted)'}', style: GoogleFonts.poppins(fontSize: 10, color: Colors.white54)), trailing: Row(mainAxisSize: MainAxisSize.min, children: [
                IconButton(icon: const Icon(Icons.delete_forever, color: Colors.redAccent, size: 18), onPressed: () async {
                  bool confirm = await showDialog(context: context, builder: (ctx)=> AlertDialog(backgroundColor: const Color(0xFF1E1E1E), title: Text(AppStrings.delete, style: GoogleFonts.poppins(color: Colors.white, fontSize: 14)), content: Text("${col['name']} Rs ${col['amount']} delete?", style: GoogleFonts.poppins(color: Colors.white70, fontSize: 12)), actions: [TextButton(onPressed: ()=> Navigator.pop(ctx,false), child: const Text("Nahi")), TextButton(onPressed: ()=> Navigator.pop(ctx,true), child: const Text("Haan Delete", style: TextStyle(color: Colors.red))) ]))?? false;
                  if(!confirm) return;
                  try{ await FirebaseService.collectionsCol.doc(col['docId']).delete(); widget.onCollectionRemove(col['docId']); setSheetState(()=> collectionsList.removeWhere((x)=> x['docId']==col['docId'])); }catch(e){}
                }),
                ElevatedButton(style: ElevatedButton.styleFrom(backgroundColor: Colors.orange, padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4), minimumSize: const Size(50, 30)), child: Text(AppStrings.undo, style: GoogleFonts.poppins(color: Colors.white, fontSize: 10, fontWeight: FontWeight.bold)), onPressed: () async {
                  try{
                    String phone = col['phone'].toString(); String billMonth = col['billMonth'].toString(); int amount = FirebaseService.parseAmount(col['amount']);
                    await FirebaseService.collectionsCol.doc(col['docId']).delete();
                    widget.onCollectionRemove(col['docId']);
                    Map<String, dynamic> restoredBill = {'name': col['name'], 'phone': phone, 'amount': amount, 'package': col['package']?? '10 Mbps', 'isPaid': false, 'date': DateTime.now().toIso8601String(), 'billMonth': billMonth, 'createdAt': DateTime.now().millisecondsSinceEpoch, 'id': FirebaseService.genBillId(phone, billMonth)};
                    await FirebaseService.billsCol.doc(restoredBill['id']).set(restoredBill);
                    setState(()=> widget.bills.add(restoredBill));
                    // Ek jagah se Due update
                    for(var u in widget.users){ if(u['phone'].toString()==phone){ double oldDue = FirebaseService.parseAmount(u['pendingDue']).toDouble(); double newDue = oldDue + amount; u['pendingDue'] = newDue; await FirebaseService.updateUserDue(phone, newDue); break; } }
                    widget.onUpdate(); widget.onUsersUpdate();
                    setSheetState(()=> collectionsList.removeWhere((x)=> x['docId']==col['docId']));
                  }catch(e){ ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error $e'), backgroundColor: Colors.red, duration: Duration(seconds: 5))); }
                }),
              ])));
            })),
          ]));
        });
      });
    });
  }

  void showPaymentDialog(var bill, int realIndex) {
    TextEditingController paidCtrl = TextEditingController(text: bill['amount'].toString());
    showDialog(context: context, builder: (c) => AlertDialog(backgroundColor: const Color(0xFF1E1E1E), title: Text("${bill['name']} - Fee Jama", style: const TextStyle(color: Colors.white, fontSize: 16)), content: Column(mainAxisSize: MainAxisSize.min, children: [
      TextField(controller: paidCtrl, keyboardType: TextInputType.number, style: const TextStyle(color: Colors.white), decoration: InputDecoration(labelText: "Kitna Jama?", filled: true, fillColor: const Color(0xFF2A2A2A), border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)))),
      ListTile(dense: true, leading: const Icon(Icons.check_circle, color: Colors.green, size: 20), title: Text(AppStrings.normalJama, style: GoogleFonts.poppins(color: Colors.white, fontSize: 12)), onTap: () => Navigator.pop(c, "normal")),
      ListTile(dense: true, leading: const Icon(Icons.person_add_alt_1, color: Colors.blue, size: 20), title: Text(AppStrings.activeWithoutBill, style: GoogleFonts.poppins(color: Colors.white, fontSize: 12)), onTap: () => Navigator.pop(c, "active_without_bill")),
      ListTile(dense: true, leading: const Icon(Icons.warning_amber, color: Colors.orange, size: 20), title: Text(AppStrings.billDue, style: GoogleFonts.poppins(color: Colors.white, fontSize: 12)), onTap: () => Navigator.pop(c, "bill_due")),
    ]), actions: [TextButton(onPressed: ()=>Navigator.pop(c), child: const Text("Cancel"))])).then((action) async {
      if(action==null) return;
      double total = double.tryParse(bill['amount'].toString())?? 0; double paid = double.tryParse(paidCtrl.text)?? 0; if(paid <= 0) return;
      if(action=='normal'){
        for (var u in widget.users) { if (u['phone'].toString() == bill['phone'].toString()) { await FirebaseService.updateUserDue(bill['phone'].toString(), total - paid); u['pendingDue'] = total - paid; break; } }
        await FirebaseService.billsCol.doc(bill['id']?? "${bill['phone']}_${bill['billMonth']}_${bill['createdAt']}").delete();
        String colId = DateTime.now().millisecondsSinceEpoch.toString();
        Map<String, dynamic> colData = {"name": bill['name'], "phone": bill['phone'].toString(), "amount": paid, "package": bill['package'], "date": DateTime.now().toIso8601String(), "billMonth": bill['billMonth'], "type": paid >= total? "full" : "partial", "id": colId};
        widget.onCollectionAdd(colData); await FirebaseService.collectionsCol.doc(colId).set(colData);
        setState(()=> widget.bills.removeAt(realIndex)); widget.onUpdate(); widget.onUsersUpdate();
        if(mounted){ ScaffoldMessenger.of(context).clearSnackBars(); final sb = SnackBar(duration: const Duration(seconds: 5), content: Text("${bill['name']} Paid! ${bill['billMonth']}"), backgroundColor: Colors.green, action: SnackBarAction(label: AppStrings.undo, textColor: Colors.white, onPressed: ()=> _showUndoList(bill['billMonth']))); ScaffoldMessenger.of(context).showSnackBar(sb); Timer(const Duration(seconds: 5), (){ if(mounted) ScaffoldMessenger.of(context).hideCurrentSnackBar(); }); }
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF121212),
      appBar: AppBar(backgroundColor: const Color(0xFF121212), title: Text("Bills - ${filteredBills.length}", style: GoogleFonts.poppins(color: Colors.white, fontWeight: FontWeight.bold)), actions: [IconButton(icon: const Icon(Icons.undo, color: Colors.orange), onPressed: ()=> _showUndoList(selectedMonthFilter)), IconButton(icon: const Icon(Icons.refresh), onPressed: autoGenerateExpiredBills)]),
      body: Column(children: [
        Padding(padding: const EdgeInsets.all(12), child: Row(children: [
          Expanded(child: TextField(controller: searchCtrl, style: const TextStyle(color: Colors.white), onChanged: (v)=>setState(()=>search=v), decoration: InputDecoration(hintText: "Search...", prefixIcon: const Icon(Icons.search, color: Colors.white38), filled: true, fillColor: const Color(0xFF1E1E1E), border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none)))),
          SizedBox(width: 8),
          DropdownButton<String>(value: selectedMonthFilter, dropdownColor: Color(0xFF1E1E1E), style: TextStyle(color: Colors.white, fontSize: 11), items: last12Months.map((m)=> DropdownMenuItem(value: m, child: Text(m, style: TextStyle(fontSize: 11)))).toList(), onChanged: (v){ if(v!=null) setState(()=> selectedMonthFilter=v); })
        ])),
        Row(children: [const SizedBox(width: 12), _filterChip("All"), _filterChip("Pending")]),
        const SizedBox(height: 10),
        Expanded(child: filteredBills.isEmpty? Center(child: Text("Koi bill nahi - Month $selectedMonthFilter", style: GoogleFonts.poppins(color: Colors.white54))) : ListView.builder(itemCount: filteredBills.length, itemBuilder: (c, i) {
          var b = filteredBills[i]; int realIndex = widget.bills.indexWhere((x) => x['phone'].toString() == b['phone'].toString() && x['billMonth'] == b['billMonth']); if(realIndex == -1) realIndex = widget.bills.indexOf(b);
          return Container(margin: const EdgeInsets.symmetric(horizontal: 12, vertical: 6), decoration: BoxDecoration(color: const Color(0xFF1E1E1E), borderRadius: BorderRadius.circular(15)), child: ListTile(leading: const CircleAvatar(backgroundColor: Colors.orange, child: Icon(Icons.pending, color: Colors.white)), title: Text(b['name'], style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold)), subtitle: Text("${b['package']??''} - Rs. ${b['amount']} - ${b['billMonth']}", style: const TextStyle(color: Colors.white54, fontSize: 11)), trailing: Row(mainAxisSize: MainAxisSize.min, children: [IconButton(icon: const Icon(Icons.picture_as_pdf, color: Colors.white70, size: 20), onPressed: ()=>showBillPdf(b)), IconButton(icon: const Icon(Icons.payments, color: Colors.greenAccent), onPressed: ()=>showPaymentDialog(b, realIndex))])));
        })),
      ]),
    );
  }
  Widget _filterChip(String label) => Padding(padding: const EdgeInsets.only(right: 8), child: ChoiceChip(label: Text(label), selected: filter == label, selectedColor: const Color(0xFF7C4DFF), backgroundColor: const Color(0xFF2A2A2A), labelStyle: const TextStyle(color: Colors.white), onSelected: (v)=>setState(()=>filter=label)));
}